#!/usr/bin/env bash
# digging ip address from a subdomain name

no_arg=$#
arg1=$1
arg2=$2

get_ip_and_print() {
    dig $url | grep -A1 'ANSWER SECTION:' | awk -v url="$subdomain" '{ if (NR==2) {print "The subdomain "url" is a "$4" record and points to "$5}}'
}

get_the_url() {
    if [ $no_arg -eq 1 ]
    then
        subdomains=("www" "lb-01" "web-01" "web-02")
        for i in {0..3}; do
            subdomain=${subdomains[$i]}
            url=${subdomains[$i]}"."$arg1
            get_ip_and_print
        done
    else
        url=$arg2"."$arg1
        subdomain=$arg2
        get_ip_and_print
    fi
}


get_the_url