#!/usr/bin/env bash
# transfering a file to a remote server using scp

if [ $# -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -R -i $4 $1 "$3@$2": 
fi