#!/usr/bin/env bash
# configuring a new server

apt-get update -y
apt install nginx -y
mkdir -p /var/www/
echo "Hello World!" > /var/www/html/index.html
sed  -i "\|root /var/www/html;|a\\\tadd_header X-Served-By \$hostname;" /etc/nginx/sites-enabled/default
nginx -s reload
