#!/usr/bin/env bash
# debuging

printf "server {
    listen 80;

    index index.html index.htm;
    
    location /hbnb_static {
        alias /data/web_static/current/;
        index index.html index.htm;
    }
}
" > /etc/nginx/sites-available/default
service nginx restart
