#!/usr/bin/env bash
# killing a process
echo $$> /var/run/myscript.pid

sigquit_handler(){
    rm -r /var/run/myscript.pid
    exit
}

trap 'echo I hate the kill command && sigquit_handler' SIGTERM
trap "echo Y U no love me?!" SIGINT
trap sigquit_handler SIGQUIT

while :
do
    echo To infinity and beyond
    sleep 2
done