#!/usr/bin/env bash
# displaying 12 hours and minutes
hour=0
minutes=0
echo Hours: $hour
while [ $hour -lt 13 ]
do
	if [ $minutes -eq 59 ]
	then
		hour=$(( hour + 1 ))
		if [ $hour -ne 13 ]
		then
			echo Hour: $hour
		fi
		minutes=0
	fi
	minutes=$((minutes + 1))
	if [ $hour -ne 13 ]
	then
		echo $minutes
	fi
done
